validate_ot_nexson.py: ERROR: An ID Reference did not match a previous ID ("@target": "node10") in "edge(id=edge1)"
validate_ot_nexson.py: ERROR: Disconnected graph found instead of tree including root nodes:"node0", "node1" in "tree(id=tree1)"
