validate_ot_nexson.py: ERROR: An ID Reference did not match a previous ID ("@target": "node10") in "edge(id=edge1)"
