validate_ot_nexson.py: ERROR: An ID Reference did not match a previous ID ("@source": "node10") in "edge(id=edge0)"
validate_ot_nexson.py: ERROR: Disconnected graph found instead of tree including root nodes:"node0", "node2" in "tree(id=tree1)"
