validate_ot_nexson.py: ERROR: An ID Reference did not match a previous ID ("@source": "node10") in "edge(id=edge0)"
