validate_ot_nexson.py: ERROR: An ID Reference did not match a previous ID ("@otus": "otus42") in "trees"
