validate_ot_nexson.py: ERROR: Multiple nodes in a tree were flagged as being the root node ("node1" was not the first) in "node in tree(id=tree1)"
